stages:
  - build

build-image:
  stage: build
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin registry.eliashouse.ddns.net
  script:
    - docker build -t "$IMAGE_TAG" Java/chessAB/
    - docker push "$IMAGE_TAG"
  only:
    - main
