stages:
  - build

build-image:
  stage: build
  image: docker:latest

  services:
    - name: docker:dind
      command: ["--insecure-registry=registry.eliashouse.ddns.net:80"]

  variables:
    IMAGE_TAG: registry.eliashouse.ddns.net:80/root/chessabalgo:$CI_COMMIT_REF_SLUG

  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin registry.eliashouse.ddns.net:80

  script:
    - docker build -t "$IMAGE_TAG" Java/chessAB/
    - docker push "$IMAGE_TAG"

  only:
    - main